# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e51e9ed96161c321e81da0c5d07188e4"
name = "marketing"
handle = "marketing-67"
application_url = "https://false-therefore-ambien-exclude.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ohsolutions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_products"

[auth]
redirect_urls = [
  "https://false-therefore-ambien-exclude.trycloudflare.com/auth/callback",
  "https://false-therefore-ambien-exclude.trycloudflare.com/auth/shopify/callback",
  "https://false-therefore-ambien-exclude.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
